# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: WLED Matrix Manager
version: "0.9.4"
slug: wled_matrix_manager
description: Create and manage pixel-art scenes for WLED LED matrices
url: "https://github.com/aiakos-k/WLED-Matrix-Manager/tree/main/wled_matrix_manager"
image: "ghcr.io/aiakos-k/{arch}-addon-wled-matrix-manager"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
ingress: true
ingress_port: 8000
ingress_entry: /
panel_icon: mdi:led-strip-variant
panel_title: WLED Matrix Manager
homeassistant_api: true
hassio_api: true
hassio_role: admin
map:
  - share:rw
  - addon_config:rw
options:
  log_level: info
schema:
  log_level: "list(debug|info|warning|error)?"
