"""Add TOTP fields to User model

Revision ID: 7f8g9h0i1j2k
Revises: 6e7f8g9h0i1j
Create Date: 2025-11-22 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8g9h0i1j2k'
down_revision = '6e7f8g9h0i1j'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
