# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"

labels:
  org.opencontainers.image.title: "Home Assistant WLED Matrix Manager Add-on"
  org.opencontainers.image.description: "Modernes Home Assistant Add-on mit FastAPI Backend und React Frontend"
  org.opencontainers.image.source: "https://github.com/aiakos-k/WLEDMatrixManager"
  org.opencontainers.image.licenses: "EUPL-1.2"
  org.opencontainers.image.version: "0.9.0"

args:
  TEMPIO_VERSION: "2024.11.2"
